# Generated by Django 5.2.10 on 2026-01-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=120)),
                ('dosage', models.CharField(blank=True, max_length=120)),
                ('time_of_day', models.TimeField()),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time_of_day', '-created_at'],
            },
        ),
    ]
